### ISSUE TITLE
webfonts support ? 

### ISSUE THREAD

**Issue by juanpabloaj** [stomita/heroku-buildpack-phantomjs#21]
how I can get webfonts support ?

**Comment by sdesalas** [comment]
Hi @juanpabloaj, that depends on the version of IE you have installed. 

When I render http://triflejs.org there seems to be no problem rendering "Roboto Condensed" used througout. But then I'm using IE11.

**Comment by nesQuick** [comment]
With phantomjs 2 you will get webfont support. Finding a working buildpack for phantomjs 2 is kinda hard. I ended up after searching 1000 forks using a adjusted working fork from somewhere https://github.com/nesQuick/heroku-buildpack-phantomjs/pull/1 :warning:  but this requires cedar-14 and the binary is hosted at some random person on the internet
