### ISSUE TITLE
phantomjs v2 support?

### ISSUE THREAD

**Issue by Carpela** [stomita/heroku-buildpack-phantomjs#23]
Just a question as to whether there are plans to add phantomjs v2.0 support here. Probably beyond my skill to do much to help, though I can have a go.

**Comment by Carpela** [comment]
Actually, I see someone's made a very small commit on a pull request. Could have done that one myself. Any idea what the issue is with it? Something about not compiling on linux?

**Comment by stomita** [comment]
I haven't enough checked the validity of phantomjs v2 in heroku env yet. You can use updated buildpack version on branch 2.0

**Comment by stomita** [comment]
The binary for linux is still not available. This buildpack will not build from source code. Please watch it.
