### ISSUE TITLE
buildpack crashes heroku

### ISSUE THREAD

**Issue by christianhaller** [stomita/heroku-buildpack-phantomjs#25]
After I set 
````
heroku config:add BUILDPACK_URL=https://github.com/stomita/heroku-buildpack-phantomjs.git
````
my dyno is crashing (at=error code=H10 desc="App crashed")

**Comment by christianhaller** [comment]
It was my fault.

**Comment by samrispaud** [comment]
@christianhaller what was the fix? I'm trying to deploy a rails app with phantomjs via heroku docker and I seem to be getting this same issue

**Comment by christianhaller** [comment]
@samrispaud I remember that it was something not related to heroku. It was broken on my local machine too.
