### ISSUE TITLE
Phantom 2.0?

### ISSUE THREAD

**Issue by tomgallagher** [stomita/heroku-buildpack-phantomjs#32]
Any chance you could bump up to 2.0?

**Comment by squallstar** [comment]
@tomgallagher you can use this fork https://github.com/srbartlett/heroku-buildpack-phantomjs-2.0

**Comment by tomgallagher** [comment]
Thanks for letting me know. I had seen the link.

The reason I was asking is that I'm a bit new to the multiple buildpacks world.

It is well within my powers to do this:

`$ heroku buildpacks:add https://github.com/stomita/heroku-buildpack-phantomjs`

The install instructions for the fork are a bit beyond me, if I'm honest, and I don't want to start doing stuff I don't understand.

**Comment by squallstar** [comment]
@tomgallagher I'm currently using the multi buildpack (https://github.com/ddollar/heroku-buildpack-multi) and then I have a `.buildpacks` file with the following:

```
https://github.com/heroku/heroku-buildpack-nodejs
https://github.com/srbartlett/heroku-buildpack-phantomjs-2.0.git#bda8c09bc97875737fdecce208359605e4e5162a
```

**Comment by tomgallagher** [comment]
So, for example, I don't use the multi buildpack (https://github.com/ddollar/heroku-buildpack-multi) but I added the stomita phantom js and there seemed to be native support for it on Heroku. And then I would need to install all the libraries? 
libicu52
libjpeg8
libfontconfig
libwebp5
But I thought phantomJS was a self-sufficient build?

**Comment by stomita** [comment]
Added support of 2.1.1 in #33

**Comment by tomgallagher** [comment]
Thanks very much
