### ISSUE TITLE
phantomjs 2.1.1 intermitmently can't be extracted on heroku

### ISSUE THREAD

**Issue by phuongnd08** [stomita/heroku-buildpack-phantomjs#37]
I'm getting this:
```
remote: =====> Detected Framework: PhantomJS
remote: -----> Fetching PhantomJS 2.1.1 binaries at https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
remote: -----> Extracting PhantomJS 2.1.1 binaries to /tmp/build_b8c3631cd930837861d76051e5f17517/vendor/phantomjs
remote: bzip2: (stdin) is not a bzip2 file.
remote: tar: Child returned status 2
remote: tar: Error is not recoverable: exiting now
```

On closer inspection, I find that `https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2` is not predictable. Occasionally it returns a forbidden error xml file from S3.

**Comment by sonicgao** [comment]
me too, #36 fixed this, when will be merge?

**Comment by phuongnd08** [comment]
#36 doesn't fix this. This is issue with bitbucket return broken tar ball.

**Comment by bewallyt** [comment]
Am having this issue as well. Were you guys able to get this resolved?

**Comment by buzibu** [comment]
I tried to open the URL in browser and actually the bitbucket file does not exist every time when I load the page. 
PhantomJS 2.1.1 binaries at https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 

After several retries I succeeded to download the file with browser and after that successfully pushed to heroku

**Comment by stomita** [comment]
Changed download url to Github in #39 and it must be much stabler than before.
