### ISSUE TITLE
Problem with installing older version

### ISSUE THREAD

**Issue by dorukeker** [stomita/heroku-buildpack-phantomjs#38]
Hello,

I am not sure if this is the place to ask. But since you'd have experience about the buildpack, I'll give a shot.

I have a NodeJS application that is also using the PhantomJS.

My set up is 1.x of PhantomJS and 1.x of the node module `phantom`. And on Heroku I had multi-buildpacks `heroku/node` and this buildpack.

PhantomJS updated to 2.x and the node module is updated with it. However this current change breaks my current code. I will be fixing it for the new version. But for now I would like to run an older version of PhantomJS on Heroku so my existing code will work until I fix it.

To do that I ran the following code on Heroku
```shell
$ heroku buildpacks:set heroku/nodejs
Buildpack set. Next release on tripfoldit-staging will use heroku/nodejs.
Run git push heroku master to create a new release using this buildpack.

$ heroku buildpacks:add https://github.com/stomita/heroku-buildpack-phantomjs.git#1.9.2
Buildpack added. Next release on tripfoldit-staging will use:
  1. heroku/nodejs
  2. https://github.com/stomita/heroku-buildpack-phantomjs.git#1.9.2
Run git push heroku master to create a new release using these buildpacks.
```

Then I git push my repo and watch it built as expected. However after that I run my code and got a message 'Phantom js is not installed!'

My assumption is that during the successful build the PhantomJS is installed. Am I missing anything? Any suggestions?

Cheers,
Doruk

**Comment by akshaylive** [comment]
+1

**Comment by akshaylive** [comment]
@dorukeker did you find a workaround?

**Comment by dorukeker** [comment]
@akshaylive i have not found a solution for that. I Annie using phantojs-node https://github.com/amir20/phantomjs-node/ which has phantomjs prebuilt in it.
So you only need the nodejs build pack. And the nose module takes care of the phantom. 
But ofcourse it comes with 2.x and you need to rewrite your code.
Good luck :)
